### ISSUE TITLE
spacy_initialize error

### ISSUE THREAD

**Issue by fabianaiolfi** [UniLuFS2020-ReplicationSeminar/OSF2#3]
Hello @Oldscha and @simonweigold 

You may come across the following or similar error when running [02 - create corpus.R](https://github.com/UniLuFS2020-ReplicationSeminar/OSF2/blob/cce3d5dd81f26ae41ab9a8420f72b4bdacb76731/scripts/02%20-%20create%20corpus.R):

```R
Error: ModuleNotFoundError: No module named 'spacy'
```

This error is caused by this line:

https://github.com/UniLuFS2020-ReplicationSeminar/OSF2/blob/cce3d5dd81f26ae41ab9a8420f72b4bdacb76731/scripts/02%20-%20create%20corpus.R#L6

As you can see, this line references a path specific to my machine (`/Users/aiolf1/`), so it's not going to work on your device. I'm currently unsure how to make this line work on other devices.

The script uses [spacyr](https://spacy.io/universe/project/spacyr) for [Named Entity Recognition (NER)](https://en.wikipedia.org/wiki/Named-entity_recognition). We're using NER to see which instances of the term "Amazon" reference the company (and not, e.g., the rainforest). spacyr requires Python to run in the background … long story short: The script may not run on your machine because of Python. And it could be a very long and painful process installing Python and get it running on your machines.

So to fix this problem I suggest the following: The script creates the object `guardian_amazon_corpus` containing ~23k articles that reference Amazon as a company. [You can download this object from my Dropbox with this link](https://www.dropbox.com/s/uyued66ufsz8whx/guardian_amazon_corpus.RData?dl=0) and then load the .RData file at the beginning of your script so we're all working with the same corpus:

```R
load("guardian_amazon_corpus.RData")
```

**Comment by Oldscha** [comment]
Thank you very much @fabianaiolfi for the creation of the text corpus and the anticipatory hint. I took your suggested solution and downloaded the dataset from your Dropbox. It works fine!
